image: Visual Studio 2017
services:
- mysql
build_script:
- dotnet --info
before_test:
- cmd: |-
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -u root --password=Password12! < .ci\server\init.sql
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -u root --password=Password12! < .ci\server\init_sha256.sql
test_script:
- ps: .\.ci\test.ps1
after_test:
- cmd: |-
    dotnet pack src\MySqlConnector\MySqlConnector.csproj -c Release
    dotnet pack src\MySqlConnector.Authentication.Ed25519\MySqlConnector.Authentication.Ed25519.csproj -c Release
    dotnet pack src\MySqlConnector.Logging.log4net\MySqlConnector.Logging.log4net.csproj -c Release
    dotnet pack src\MySqlConnector.Logging.Microsoft.Extensions.Logging\MySqlConnector.Logging.Microsoft.Extensions.Logging.csproj -c Release
    dotnet pack src\MySqlConnector.Logging.NLog\MySqlConnector.Logging.NLog.csproj -c Release
    dotnet pack src\MySqlConnector.Logging.Serilog\MySqlConnector.Logging.Serilog.csproj -c Release
notifications:
- provider: Slack
  incoming_webhook:
    secure: SRJ5fYQE4tvelyqeX3Lkv0gXta3O2pl4/+wNaqmqmcFkmYBe+U31T5YCGhipBOVhHBIZLevihOJZ78sFVJrmAFV5bHgtX/VPIKEXN+7ytis=
artifacts:
- path: src\*\bin\Release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: "jXzwnknTcQgGqjAxBzMLstPMaXy9rl3HowFns/QKaUqbUMUqXKpNLiNZKqv6tfnS"
  artifact: /.*MySqlConnector[0-9.]+nupkg/
  skip_symbols: true
  on:
    appveyor_repo_tag: true
